### ISSUE TITLE
Bootstrap service does not return 'keyless' accounts

### ISSUE THREAD

**Issue by bakhtin** [d3ledger/notary#409]
Bootstrap service endpoint `/iroha/config/accounts/{project}/{env}` returns ONLY 'active' accounts that have valid keys (i.e.,`"passive": false`). Although, there are currently 3 accounts that do not require keys, but still exist in genesis block. Namely, `gen_btc_pk_trigger@notary`, `btc_change_addresses@notary` and`notaries@notary`. Also, see a genesis block: https://github.com/d3ledger/notary/blob/develop/deploy/iroha/genesis.block. Those 'keyless' or 'passive' accounts should also be returned when invoking the endpoint.
This bug prevents from generating genesis block when invoking `/iroha/create/genesisBlock` API endpoint. It complains on those 3 missing accounts.

**Comment by yurivin** [comment]
My idea is that `/iroha/config/accounts/{project}/{env}` should not return 'passive accounts'. It should appear in genesis block without configuration. Error was that 'passive' accounts was not added in endpoint of Genesis block cration
