### ISSUE TITLE
Bootstrap endpoint `/iroha/projects/genesis` response format

### ISSUE THREAD

**Issue by bakhtin** [d3ledger/notary#410]
Bootstrap API endpoint `/iroha/projects/genesis` returns a response in the following format:
```
{  "D3": "test" }
```
I suggest to refactor the endpoint so that it returns a response in the following format:
```
{  "project": "D3": "environment": "test" }
```
This would allow to more easily parse the response without checking for presence of a certain key in the dictionary but just filter for `project` and `tag`

**Comment by yurivin** [comment]
Because there may be multiple environments for one project `environments` will be represented as array
`{  "project": "D3": "environments": ["test"] }`
