### ISSUE TITLE
Bootstrap service should have an endpoint for listing Ethereum wallets required for other services

### ISSUE THREAD

**Issue by bakhtin** [d3ledger/notary#434]
Despite there is an endpoint for Ethereum wallet generation, we can not say how many of these wallets are required. Since each notary service requires its own wallet, there should be an endpoint that returns a list of services that require a wallet with its names.

**Comment by yurivin** [comment]
We should create ethereum wallets for Withdrawal and Registration services. Also for every deposit service which count equals to count of peers. So number of ethereum wallets should be equal to peersCount+2
