### ISSUE TITLE
Illegal environment variable name in Bootstrap service

### ISSUE THREAD

**Issue by bakhtin** [d3ledger/notary#441]
Bootstrap service README says it is possible to set an environment variable to manipulate the type of Bitcoin network one want to generate a wallet in (https://github.com/d3ledger/notary/tree/develop/bootstrap#startup-configuration). The name of the environment variable is `btc.network`. This name seems illegal in Shell (particularly in Bash). It must not contain a `.` char in it.
Attempting to set this variable leads to an error:
```
$ export btc.network=MainNet
bash: export: ``btc.network=MainNet': not a valid identifier
```
I understand, this variable can also be set up in `applications.properties` file. But I would like to be able to set up this variable as an environment variable as well

**Comment by Mingela** [comment]
@bakhtin during environment variables reading all the keys are transformed in the following way:
`key.replace('.', '_')` try to set `btc_network` or `BTC_NETWORK` instead

**Comment by bakhtin** [comment]
got it, thanks. Closing the issue
