### ISSUE TITLE
Bootstrap service does not return some accounts for GB

### ISSUE THREAD

**Issue by bakhtin** [d3ledger/notary#477]
Bootstrap service endpoint `/iroha/config/accounts/{project}/{env}/{peersCount}` missing some accounts from its output value. Namely, the following accounts `@notary` domain are missing:
- notary
- rmq
- mst_btc_registration_service
- btc_withdrawal_service
- btc_consensus_collector
- btc_withdrawal_signature_collector

As far as I can tell, all of them are multisignature accounts and its quorum is subject to change depending on `peersCount` parameter

**Comment by yurivin** [comment]
There where two problems.
1. Some accounts where set as passive.
2. Some accounts was not included in genesis block by creators

**Comment by bakhtin** [comment]
Another account is missing: `registration_service_primary@notary`
