### ISSUE TITLE
docker-compose up fails

### ISSUE THREAD

**Issue by oimou** [d3ledger/notary#97]
At 893dc9d, I got an error when I run docker-compose up.

# Environment
* macOS 10.13.3

# What I did:
1. git pull (to get the latest master branch)
2. docker-compose pull (just in case)
3. docker-compose down
4. docker-compose build
5. docker-compose up

Log is here:
https://gist.github.com/oimou/aed735081de54e0989d8f8103aa6430e

**Comment by Alexey-N-Chernyshov** [comment]
Here is a missing Ethereum password config. We have moved to testnet Ropsten for Ethereum and have added config with Ethereum password to .gitignore to not expose it. So, you can ask @laSinteZ for password.
